Name: find_orphaned_rpm_etc_files
Summary: Finds orphaned rpm files under /etc
Version: 0.2
Release: 2
License: GPL
Group: Utilities/System
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArchitectures: noarch

%description 
Finds orphaned rpm files under /etc like *.rpmnew, *.rpmsave or *.rpmorig
automatically generated by rpm on update. RPM created these files if a software
update has taken place and it cannot update the configuration files itself.
These files need to be solved by root manually.

%install
rm -fr $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/etc/cron.daily
install -m 755 $RPM_SOURCE_DIR/find_orphaned_rpm_etc_files $RPM_BUILD_ROOT/etc/cron.daily/find_orphaned_rpm_etc_files

%files
%doc AUTHORS COPYING README
/etc/cron.daily/find_orphaned_rpm_etc_files
