#!/bin/sh
#
# Author: Georg Lutz <georg NOSPAM AT georglutz DOT de>
# Find orphaned config files under /etc automatically created by rpm that need manual fix
#
#    Copyright (C) 2008-2009 Georg Lutz <georg AT NOSPAM georglutz DOT de>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

found=`/usr/bin/find /etc -name "*.rpmnew" -o -name "*.rpmsave" -o -name "*.rpmorig" 2>/dev/null`

if [ "$found" != "" ]; then
    echo "Found files in /etc ending with *.rpmnew, *.rpmsave or *.rpmorig:"
    echo ""
    echo $found
    echo ""
    echo ""
fi
